# Generated by Django 5.0.2 on 2025-11-13 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('pk_camion', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('capacite_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('est_affecter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('pk_chauffeur', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_client', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_client', models.CharField(choices=[('entreprise', 'Entreprise'), ('particulier', 'Particulier')], max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('score_fidelite', models.IntegerField(default=100)),
                ('etat_paiement', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('bloqué', 'Bloqué')], default='bon', max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieConteneur',
            fields=[
                ('pk_compagnie', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conteneur',
            fields=[
                ('pk_conteneur', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('numero_conteneur', models.CharField(max_length=30, unique=True)),
                ('type_conteneur', models.CharField(blank=True, max_length=50, null=True)),
                ('poids', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ContratTransport',
            fields=[
                ('pk_contrat', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('numero_bl', models.CharField(max_length=100)),
                ('destinataire', models.CharField(max_length=200)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avance_transport', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reliquat_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut_caution', models.CharField(choices=[('bloquée', 'Bloquée'), ('débloquée', 'Débloquée')], default='bloquee', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_limite_retour', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('signature_chauffeur', models.BooleanField(default=False)),
                ('signature_client', models.BooleanField(default=False)),
                ('signature_transitaire', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('pk_entreprise', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('pk_fournisseur', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('fiabilite', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], default='bon', max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraisTrajet',
            fields=[
                ('pk_frais', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('origine', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('frais_route', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_carburant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanicien',
            fields=[
                ('pk_mecanicien', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('pk_mission', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('origine', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('en cours', 'En cours'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], default='en cours', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MissionConteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaiementMission',
            fields=[
                ('pk_paiement', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_transitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution_est_retiree', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceReparee',
            fields=[
                ('pk_piece', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nom_piece', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('moteur', 'Moteur'), ('transmission', 'Transmission'), ('suspension', 'Suspension & Direction'), ('freinage', 'Freinage'), ('electrique', 'Éléments électriques'), ('eclairage', 'Éclairage & Signalisation'), ('auxiliaire', 'Systèmes auxiliaires'), ('carrosserie', 'Carrosserie & Structure'), ('pneumatique', 'Pneumatiques & Roues'), ('alimentation', "Système d'alimentation")], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence fabricant', max_length=50, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrestationDeTransports',
            fields=[
                ('pk_presta_transport', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('prix_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('pk_reparation', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('date_reparation', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReparationMecanicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transitaire',
            fields=[
                ('pk_transitaire', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('score_fidelite', models.IntegerField(default=100)),
                ('etat_paiement', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('bloqué', 'Bloqué')], default='bon', max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('pk_utilisateur', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('utilisateur', 'Utilisateur'), ('chauffeur', 'Chauffeur')], default='utilisateur', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Utilisateur',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Cautions',
            fields=[
                ('pk_caution', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_rembourser', models.BooleanField(default=False)),
                ('est_rembourser', models.BooleanField(default=True)),
                ('montant_rembourser', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.chauffeur')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('pk_affectation', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('date_affectation', models.DateField(default=django.utils.timezone.now)),
                ('date_fin_affectation', models.DateField(blank=True, null=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.camion')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.chauffeur')),
            ],
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('nom', 'type_client', 'telephone'), name='unique_client'),
        ),
        migrations.AddField(
            model_name='cautions',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.client'),
        ),
        migrations.AddConstraint(
            model_name='compagnieconteneur',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_compagnie'),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.client'),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.compagnieconteneur'),
        ),
        migrations.AddField(
            model_name='cautions',
            name='conteneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.conteneur'),
        ),
        migrations.AddField(
            model_name='contrattransport',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.camion'),
        ),
        migrations.AddField(
            model_name='contrattransport',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.chauffeur'),
        ),
        migrations.AddField(
            model_name='contrattransport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.client'),
        ),
        migrations.AddField(
            model_name='contrattransport',
            name='conteneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.conteneur'),
        ),
        migrations.AddField(
            model_name='cautions',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.contrattransport'),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(fields=('nom', 'secteur_activite', 'email_contact', 'date_creation'), name='unique_entreprise'),
        ),
        migrations.AddField(
            model_name='contrattransport',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.entreprise'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.entreprise'),
        ),
        migrations.AddField(
            model_name='camion',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.entreprise'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.entreprise'),
        ),
        migrations.AddConstraint(
            model_name='fraistrajet',
            constraint=models.UniqueConstraint(fields=('origine', 'destination'), name='unique_frais_trajet'),
        ),
        migrations.AddField(
            model_name='mission',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.contrattransport'),
        ),
        migrations.AddField(
            model_name='mission',
            name='frais_trajet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.fraistrajet'),
        ),
        migrations.AddField(
            model_name='missionconteneur',
            name='conteneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.conteneur'),
        ),
        migrations.AddField(
            model_name='missionconteneur',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.mission'),
        ),
        migrations.AddField(
            model_name='paiementmission',
            name='caution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.cautions'),
        ),
        migrations.AddField(
            model_name='paiementmission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.mission'),
        ),
        migrations.AddField(
            model_name='piecereparee',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.fournisseur'),
        ),
        migrations.AddField(
            model_name='prestationdetransports',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.camion'),
        ),
        migrations.AddField(
            model_name='prestationdetransports',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.client'),
        ),
        migrations.AddField(
            model_name='prestationdetransports',
            name='contrat_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.contrattransport'),
        ),
        migrations.AddField(
            model_name='paiementmission',
            name='prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.prestationdetransports'),
        ),
        migrations.AddField(
            model_name='mission',
            name='prestation_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.prestationdetransports'),
        ),
        migrations.AddField(
            model_name='reparation',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.camion'),
        ),
        migrations.AddField(
            model_name='reparation',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.chauffeur'),
        ),
        migrations.AddField(
            model_name='piecereparee',
            name='reparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.reparation'),
        ),
        migrations.AddField(
            model_name='reparationmecanicien',
            name='mecanicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.mecanicien'),
        ),
        migrations.AddField(
            model_name='reparationmecanicien',
            name='reparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.reparation'),
        ),
        migrations.AddConstraint(
            model_name='transitaire',
            constraint=models.UniqueConstraint(fields=('nom', 'telephone'), name='unique_transitaire'),
        ),
        migrations.AddField(
            model_name='prestationdetransports',
            name='transitaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transitaire'),
        ),
        migrations.AddField(
            model_name='contrattransport',
            name='transitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transitaire'),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='transitaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transitaire'),
        ),
        migrations.AddField(
            model_name='cautions',
            name='transitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transitaire'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(fields=('chauffeur', 'camion', 'date_affectation'), name='unique_affectation'),
        ),
        migrations.AddConstraint(
            model_name='chauffeur',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom', 'email', 'entreprise'), name='unique_chauffeur'),
        ),
        migrations.AddConstraint(
            model_name='camion',
            constraint=models.UniqueConstraint(fields=('immatriculation', 'modele', 'entreprise'), name='unique_camion'),
        ),
        migrations.AddConstraint(
            model_name='missionconteneur',
            constraint=models.UniqueConstraint(fields=('mission', 'conteneur'), name='unique_mission_conteneur'),
        ),
        migrations.AddConstraint(
            model_name='paiementmission',
            constraint=models.UniqueConstraint(fields=('mission', 'caution', 'prestation'), name='unique_mission_caution'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(fields=('prestation_transport', 'contrat', 'origine', 'destination', 'date_depart'), name='unique_mission'),
        ),
        migrations.AddConstraint(
            model_name='piecereparee',
            constraint=models.UniqueConstraint(fields=('nom_piece', 'reparation'), name='unique_piece_reparee'),
        ),
        migrations.AddConstraint(
            model_name='reparationmecanicien',
            constraint=models.UniqueConstraint(fields=('reparation', 'mecanicien'), name='unique_reparation_mecanicien'),
        ),
        migrations.AddConstraint(
            model_name='prestationdetransports',
            constraint=models.UniqueConstraint(fields=('camion', 'pk_presta_transport', 'contrat_transport', 'client', 'transitaire'), name='unique_presta_transport'),
        ),
        migrations.AddConstraint(
            model_name='contrattransport',
            constraint=models.UniqueConstraint(fields=('conteneur', 'client', 'transitaire', 'entreprise', 'camion', 'chauffeur', 'numero_bl', 'date_debut'), name='unique_contrat_transport'),
        ),
        migrations.AddConstraint(
            model_name='conteneur',
            constraint=models.UniqueConstraint(fields=('numero_conteneur', 'compagnie', 'client'), name='unique_conteneur'),
        ),
    ]
