# Generated by Django 5.0.2 on 2025-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattransport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='contrats/'),
        ),
    ]
