# Generated by Django 5.2.3 on 2025-06-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('utilisateur', 'Utilisateur'), ('chauffeur', 'Chauffeur')], default='utilisateur', max_length=50),
        ),
    ]
