# Generated by Django 5.2.3 on 2025-06-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilisateur',
            table='Utilisateur',
        ),
    ]
