# Generated by Django 5.0.2 on 2025-11-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_contrattransport_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='est_affecter',
            field=models.BooleanField(default=False),
        ),
    ]
