# Generated by Django 5.0.2 on 2025-11-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_chauffeur_est_affecter'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementmission',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementmission',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
    ]
