# Generated by Django 5.2.3 on 2025-07-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_utilisateur_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
    ]
