# Generated by Django 5.0.2 on 2025-12-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_cautions_montant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prestationdetransports',
            name='unique_presta_transport',
        ),
        migrations.AlterField(
            model_name='cautions',
            name='est_rembourser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contrattransport',
            name='numero_bl',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='prestationdetransports',
            constraint=models.UniqueConstraint(fields=('camion', 'contrat_transport', 'client', 'transitaire', 'date'), name='unique_presta_transport'),
        ),
    ]
