# Generated by Django 5.2.3 on 2025-07-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_remove_utilisateur_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
