# Generated by Django 5.2.3 on 2025-09-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cautions',
            old_name='transiteur',
            new_name='transitaire',
        ),
        migrations.AlterUniqueTogether(
            name='affectation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='camion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chauffeur',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='compagnieconteneur',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='conteneur',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contrattransport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='entreprise',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fraistrajet',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='missionconteneur',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paiementmission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='piecereparee',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prestationdetransports',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reparationmecanicien',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transitaire',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='email',
            field=models.EmailField(blank=True, default='inconnu@exemple.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(fields=('chauffeur', 'camion', 'date_affectation'), name='unique_affectation'),
        ),
        migrations.AddConstraint(
            model_name='camion',
            constraint=models.UniqueConstraint(fields=('immatriculation', 'modele', 'entreprise'), name='unique_camion'),
        ),
        migrations.AddConstraint(
            model_name='chauffeur',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom', 'email', 'entreprise'), name='unique_chauffeur'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('nom', 'type_client', 'telephone'), name='unique_client'),
        ),
        migrations.AddConstraint(
            model_name='compagnieconteneur',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_compagnie'),
        ),
        migrations.AddConstraint(
            model_name='conteneur',
            constraint=models.UniqueConstraint(fields=('numero_conteneur', 'compagnie', 'client'), name='unique_conteneur'),
        ),
        migrations.AddConstraint(
            model_name='contrattransport',
            constraint=models.UniqueConstraint(fields=('conteneur', 'client', 'transitaire', 'entreprise', 'camion', 'chauffeur', 'date_debut', 'date_limite_retour'), name='unique_contrat'),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(fields=('nom', 'secteur_activite', 'email_contact', 'date_creation'), name='unique_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='fraistrajet',
            constraint=models.UniqueConstraint(fields=('origine', 'destination'), name='unique_frais_trajet'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(fields=('prestation_transport', 'contrat', 'origine', 'destination', 'date_depart'), name='unique_mission'),
        ),
        migrations.AddConstraint(
            model_name='missionconteneur',
            constraint=models.UniqueConstraint(fields=('mission', 'conteneur'), name='unique_mission_conteneur'),
        ),
        migrations.AddConstraint(
            model_name='paiementmission',
            constraint=models.UniqueConstraint(fields=('mission', 'caution', 'prestation'), name='unique_mission_caution'),
        ),
        migrations.AddConstraint(
            model_name='piecereparee',
            constraint=models.UniqueConstraint(fields=('nom_piece', 'reparation'), name='unique_piece_reparee'),
        ),
        migrations.AddConstraint(
            model_name='prestationdetransports',
            constraint=models.UniqueConstraint(fields=('camion', 'pk_presta_transport', 'contrat_transport', 'client', 'transitaire'), name='unique_presta_transport'),
        ),
        migrations.AddConstraint(
            model_name='reparationmecanicien',
            constraint=models.UniqueConstraint(fields=('reparation', 'mecanicien'), name='unique_reparation_mecanicien'),
        ),
        migrations.AddConstraint(
            model_name='transitaire',
            constraint=models.UniqueConstraint(fields=('nom', 'telephone'), name='unique_transitaire'),
        ),
    ]
