# Generated by Django 5.0.2 on 2025-12-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_remove_prestationdetransports_unique_presta_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='itineraire',
            field=models.TextField(blank=True, default='Itinéraire à compléter', help_text="Décrivez l'itinéraire détaillé de la mission"),
        ),
        migrations.AlterField(
            model_name='mission',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='origine',
            field=models.CharField(max_length=200),
        ),
    ]
