# Generated by Django 5.0.2 on 2025-12-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_mission_itineraire_alter_mission_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cautions',
            name='non_rembourser',
        ),
    ]
