# Generated by Django 5.2.3 on 2025-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_rename_transiteur_cautions_transitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='est_affecter',
            field=models.BooleanField(default=False),
        ),
    ]
