# Generated by Django 5.0.2 on 2025-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_remove_non_rembourser_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cautions',
            name='est_rembourser',
        ),
        migrations.AddField(
            model_name='cautions',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('remboursee', 'Remboursée'), ('non_remboursee', 'Non remboursée'), ('consommee', 'Consommée')], default='en_attente', help_text='Statut de la caution', max_length=20),
        ),
    ]
