# Generated by Django 5.0.2 on 2025-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_replace_est_rembourser_with_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='itineraire',
            field=models.TextField(blank=True, help_text="Décrivez l'itinéraire détaillé de la mission"),
        ),
    ]
