# Generated by Django 5.0.2 on 2025-12-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_mission_itineraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattransport',
            name='lieu_chargement',
            field=models.CharField(default='Bamako', help_text='Lieu de chargement / Origine', max_length=200),
        ),
    ]
