# Generated by Django 5.0.2 on 2025-12-19 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_contrattransport_lieu_chargement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('pk_notification', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('mission_terminee', 'Mission terminée'), ('paiement_valide', 'Paiement validé'), ('mission_retard', 'Mission en retard'), ('reparation_urgente', 'Réparation urgente'), ('caution_bloquee', 'Caution bloquée'), ('info', 'Information'), ('alerte', 'Alerte')], default='info', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(choices=[('check-circle', 'Succès'), ('exclamation-triangle', 'Avertissement'), ('info-circle', 'Information'), ('times-circle', 'Erreur'), ('bell', 'Notification')], default='bell', max_length=50)),
                ('color', models.CharField(choices=[('success', 'Vert'), ('warning', 'Orange'), ('info', 'Bleu'), ('danger', 'Rouge'), ('primary', 'Bleu primaire')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.mission')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.paiementmission')),
                ('reparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.reparation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', '-created_at'], name='transport_n_utilisa_e63118_idx'), models.Index(fields=['utilisateur', 'is_read'], name='transport_n_utilisa_323111_idx')],
            },
        ),
    ]
