# Generated by Django 5.0.2 on 2025-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('remboursee', 'Remboursée'), ('non_remboursee', 'Non remboursée'), ('consommee', 'Consommée'), ('annulee', 'Annulée')], default='en_attente', help_text='Statut de la caution', max_length=20),
        ),
    ]
