# Generated by Django 5.0.2 on 2025-12-20 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_alter_cautions_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('pk_audit', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VALIDER_PAIEMENT', 'Validation de paiement'), ('TERMINER_MISSION', 'Terminer mission'), ('ANNULER_MISSION', 'Annuler mission'), ('BLOQUER_CAUTION', 'Bloquer caution'), ('DEBLOQUER_CAUTION', 'Débloquer caution'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CHANGE_PASSWORD', 'Changement de mot de passe')], help_text="Type d'action effectuée", max_length=50)),
                ('model_name', models.CharField(help_text='Nom du modèle concerné (ex: Mission, PaiementMission)', max_length=100)),
                ('object_id', models.CharField(help_text="ID de l'objet concerné", max_length=250)),
                ('object_repr', models.TextField(blank=True, help_text="Représentation textuelle de l'objet")),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Dictionnaire des changements effectués (format: {'champ': {'old': valeur, 'new': valeur}})")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent du navigateur')),
                ('utilisateur', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['utilisateur', '-timestamp'], name='transport_a_utilisa_92893b_idx'), models.Index(fields=['model_name', 'object_id'], name='transport_a_model_n_8de4b7_idx'), models.Index(fields=['-timestamp'], name='transport_a_timesta_65197e_idx'), models.Index(fields=['action'], name='transport_a_action_0ec2ad_idx')],
            },
        ),
    ]
