# Generated by Django 5.0.2 on 2025-12-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneur',
            name='statut',
            field=models.CharField(choices=[('au_port', 'Au port (disponible)'), ('en_mission', 'En mission'), ('en_maintenance', 'En maintenance')], default='au_port', help_text='Statut actuel du conteneur', max_length=20),
        ),
    ]
