# Generated by Django 5.0.2 on 2025-12-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_gestion_paie'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salaire',
            new_name='transport_s_mois_bf2682_idx',
            old_name='transport_s_mois_idx',
        ),
        migrations.RenameIndex(
            model_name='salaire',
            new_name='transport_s_statut_ac6c0f_idx',
            old_name='transport_s_statut_idx',
        ),
    ]
