# Generated by Django 5.0.2 on 2025-12-28 22:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_rename_transport_s_mois_idx_transport_s_mois_bf2682_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='date_arrivee',
            field=models.DateField(blank=True, help_text="Date d'arrivée du camion à destination", null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_dechargement',
            field=models.DateField(blank=True, help_text='Date effective du déchargement', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='jours_stationnement_facturables',
            field=models.IntegerField(default=0, help_text='Nombre de jours de stationnement facturables (après les 3 jours gratuits)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='mission',
            name='montant_stationnement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total des frais de stationnement (25 000 CFA/jour)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='mission',
            name='statut_stationnement',
            field=models.CharField(choices=[('attente', 'En attente'), ('en_stationnement', 'En stationnement (frais applicables)'), ('decharge', 'Déchargé')], default='attente', help_text='Statut du stationnement', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VALIDER_PAIEMENT', 'Validation de paiement'), ('TERMINER_MISSION', 'Terminer mission'), ('ANNULER_MISSION', 'Annuler mission'), ('BLOQUER_CAUTION', 'Bloquer caution'), ('DEBLOQUER_CAUTION', 'Débloquer caution'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('FAILED_LOGIN', 'Tentative de connexion échouée'), ('CHANGE_PASSWORD', 'Changement de mot de passe')], help_text="Type d'action effectuée", max_length=50),
        ),
    ]
