# Generated by Django 5.0.2 on 2025-12-29 23:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_mission_date_arrivee_mission_date_dechargement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementmission',
            name='frais_stationnement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais de stationnement/demurrage (25 000 CFA/jour après 3 jours gratuits)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='paiementmission',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, help_text='Montant total incluant les frais de stationnement', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
