# Generated by Django 5.0.2 on 2025-12-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_add_frais_stationnement_to_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattransport',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='actif', help_text='Statut du contrat', max_length=10),
        ),
        migrations.AddField(
            model_name='paiementmission',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', help_text='Statut du paiement', max_length=15),
        ),
    ]
