# Generated by Django 5.0.2 on 2025-12-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_contrattransport_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='frais_trajet',
        ),
        migrations.AddField(
            model_name='mission',
            name='frais_trajet_aller',
            field=models.ForeignKey(blank=True, help_text='Frais pour le trajet aller (origine → destination)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_aller', to='transport.fraistrajet', verbose_name='Frais trajet aller'),
        ),
        migrations.AddField(
            model_name='mission',
            name='frais_trajet_retour',
            field=models.ForeignKey(blank=True, help_text='Frais pour le trajet retour (destination → origine ou autre)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_retour', to='transport.fraistrajet', verbose_name='Frais trajet retour'),
        ),
    ]
