# Generated by Django 5.0.2 on 2025-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_add_frais_trajet_aller_retour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraistrajet',
            options={'verbose_name': 'Frais de trajet', 'verbose_name_plural': 'Frais de trajets'},
        ),
        migrations.RemoveConstraint(
            model_name='fraistrajet',
            name='unique_frais_trajet',
        ),
        migrations.AlterField(
            model_name='fraistrajet',
            name='pk_frais',
            field=models.CharField(editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
