# Generated by Django 5.0.2 on 2025-12-30 17:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_remove_unique_frais_trajet_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraistrajet',
            options={'ordering': ['date_trajet', 'type_trajet'], 'verbose_name': 'Frais de trajet', 'verbose_name_plural': 'Frais de trajets'},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='frais_trajet_aller',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='frais_trajet_retour',
        ),
        migrations.AddField(
            model_name='fraistrajet',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.contrattransport'),
        ),
        migrations.AddField(
            model_name='fraistrajet',
            name='date_trajet',
            field=models.DateField(blank=True, help_text="Date du trajet (généralement la date de départ pour l'aller, date de retour pour le retour)", null=True),
        ),
        migrations.AddField(
            model_name='fraistrajet',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frais_trajets', to='transport.mission'),
        ),
        migrations.AddField(
            model_name='fraistrajet',
            name='type_trajet',
            field=models.CharField(choices=[('aller', 'Aller'), ('retour', 'Retour')], default='aller', help_text='Type de trajet: aller ou retour', max_length=10),
        ),
        migrations.AlterField(
            model_name='fraistrajet',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fraistrajet',
            name='frais_carburant',
            field=models.DecimalField(decimal_places=2, help_text='Frais de carburant pour ce trajet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='fraistrajet',
            name='frais_route',
            field=models.DecimalField(decimal_places=2, help_text='Frais de route pour ce trajet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='fraistrajet',
            name='origine',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='fraistrajet',
            constraint=models.UniqueConstraint(fields=('mission', 'contrat', 'type_trajet'), name='unique_frais_par_mission_type'),
        ),
    ]
