# Generated by Django 5.0.2 on 2026-01-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_frais_trajet_avec_mission_contrat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('remboursee', 'Remboursée'), ('non_remboursee', 'Non remboursée'), ('consommee', 'Consommée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', help_text='Statut de la caution', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrattransport',
            name='date_debut',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contrattransport',
            name='date_limite_retour',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contrattransport',
            name='destinataire',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contrattransport',
            name='numero_bl',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contrattransport',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='actif', help_text='Statut du contrat', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_depart',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_retour',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], db_index=True, default='en cours', max_length=10),
        ),
    ]
