# Generated by Django 5.0.2 on 2026-02-20 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_alter_cautions_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='utilisateur',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur lié à ce chauffeur (pour les notifications)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
