# Generated by Django 5.0.2 on 2026-02-22 09:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0027_transitaire_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.contrattransport'),
        ),
        migrations.AlterField(
            model_name='cautions',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cautions',
            name='montant_rembourser',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='contrattransport',
            name='statut_caution',
            field=models.CharField(choices=[('bloquee', 'Bloquée'), ('debloquee', 'Débloquée')], default='bloquee', max_length=10),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paiementmission',
            name='commission_transitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='paiementmission',
            name='frais_stationnement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais de stationnement/demurrage (25 000 CFA/jour après 3 jours gratuits)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='paiementmission',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, help_text='Montant total incluant les frais de stationnement', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='prime',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='heures_supplementaires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='salaire_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='taux_heure_supp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='total_primes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
