# Generated by Django 5.0.2 on 2026-02-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_fix_decimal_maxdigits_and_caution_protect'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.UniqueConstraint(fields=('salaire', 'type_deduction'), name='unique_deduction_per_salaire'),
        ),
        migrations.AddConstraint(
            model_name='prime',
            constraint=models.UniqueConstraint(fields=('salaire', 'type_prime'), name='unique_prime_per_salaire'),
        ),
    ]
